# site_name: TP eServices
# theme: 'material'
#
#
# site_favicon: 'img/favicon.ico'
# extra:
#   palette:
#     primary: 'Pink'
#     accent: 'grey'
#   #  text: 'Ubuntu'
#   #  code: 'Ubuntu Mono'
#   logo: 'img/logo.png'
#   social:
#     - type: 'github'
#       link: 'https://github.com/squidfunk'
#     - type: 'twitter'
#       link: 'https://twitter.com/squidfunk'
#     - type: 'linkedin'
#       link: 'https://de.linkedin.com/in/martin-donath-20a95039'
#
# pages:
#   - 'index.md'
#   - 'about.md'

site_name: TP eServices
site_description: Les Travaux Pratiques du cours eServices
site_author: Lilia Sfaxi
site_url: http://liliasfaxi.github.io/tp-eServices/

# Repository
repo_name: liliasfaxi/tp-eServices
repo_url: https://github.com/liliasfaxi/tp-eServices

# Copyright
copyright: 'Copyright &copy; 2016 - 2017 Lilia Sfaxi'

# Theme directory
theme_dir: material

site_favicon: 'img/favicon.ico'


# Options
extra:
  feature:
    tabs: false
  palette:
    primary: Light Blue
    accent: Orange
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: 'img/logo.png'

  social:
    - type: globe
      link: http://liliasfaxi.wix.com/liliasfaxi
    - type: github-alt
      link: https://github.com/liliasfaxi
    - type: twitter
      link: https://twitter.com/lillitou
    - type: linkedin
      link: https://www.linkedin.com/in/liliasfaxi/

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

# Page tree
pages:
   - 'index.md'
   - 'about.md'

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
